- name: configuring cart service
  hosts: cart
  become: yes
  tasks:
  - name: enabling nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: installing nodejs:20
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: configure user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: roboshop system user
  
  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent
  
  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete cart app directory
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent

  - name: downloading cart code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip
  

  - name: unzipping cart code
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: installing nodejs dependencies
    community.general.npm:
      path: /app

  - name: copy cart service file
    ansible.builtin.template:
      src: cart.service
      dest: /etc/systemd/system/cart.service
      
  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reexec: true

  - name: enable and start cart
    ansible.builtin.service:
      name: cart
      enabled: yes
      state: restarted

