[mongodb]
mongodb-dev.naniops.online
[catalogue]
catalogue-dev.naniops.online
[redis]
redis-dev.naniops.online
[user]
user-dev.naniops.online
[cart]
cart-dev.naniops.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.naniops.online
redis_HOST=redis-dev.naniops.online
cart_HOST=cart-dev.naniops.online
user_HOST=user-dev.naniops.online


