[mongodb]
mongodb-dev.naniops.online
[catalogue]
catalogue-dev.naniops.online
[redis]
redis-dev.naniops.online
[user]
user-dev.naniops.online
[cart]
cart-dev.naniops.online
[shipping]
shipping-dev.naniops.online
[payment]
payment-dev.naniops.online
[mysql]
mysql-dev.naniops.online
[rabbitmq]
rabbitmq-dev.naniops.online
[frontend]
frontend-dev.daws88s.online




[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.naniops.online
REDIS_HOST=redis-dev.naniops.online
USER_HOST=user-dev.naniops.online
CATALOGUE_HOST=catalogue-dev.naniops.online
CART_HOST=cart-dev.naniops.online
MYSQL_HOST=mysql-dev.naniops.online
RABBITMQ_HOST=rabbitmq-dev.naniops.online
PAYMENT_HOST=payment-dev.naniops.online
SHIPPING_HOST=shipping-dev.naniops.online





