- name: configuring payment service
  hosts: payment
  become: yes
  tasks:
  - name: istall python and gcc modules
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - python3
    -  gcc
    -  python3-devel

  - name: configure user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: roboshop system user
  
  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent
  
  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete payment app directory
    ansible.builtin.file:
      path: /tmp/payment.zip
      state: absent

  - name: downloading payment code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
      dest: /tmp/payment.zip
  

  - name: unzipping payment code
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.pip:
      requirements: requirements.txt
      executable: pip3.9
    args:
      chdir: /app

  - name: copy payment service file
    ansible.builtin.template:
      src: payment.service
      dest: /etc/systemd/system/payment.service
  
  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reexec: true

  - name: enable and start payment
    ansible.builtin.service:
      name: payment
      enabled: yes
      state: restarted
    