 # ansible-playbook -i localhost,   -e '{"instances":["mongodb","catalogue","redis","user","cart","mysql","shipping","rabbitmq","payment","frontend"]}' Roboshop.yml
- name: Create ec2 instances and route 53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-0bd66f913b1217939
    ami_id: ami-0220d79f3f480ecf5
    Env: dev
    action: create
    domain_name: naniops.online
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ Env }}"
      tags:
        project: RoboShop
        component: "{{ item }}"
        Environment: "{{ Env }}"
        Name: "{{ item }}-{{ Env }}"
    loop: "{{ instances }}"
    register: ec2_output
    when: action == "create"
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
    when: action == "create"


  - name: create route53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ Env }}.{{ domain_name }}" # mongo-dev.naniops.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: false
      overwrite: true
    loop: "{{ ec2_output.results }}"
    when: action == "create"

  - name: create route53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "roboshop-{{ Env }}.{{ domain_name }}" # mongo-dev.naniops.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: false
      overwrite: true
    loop: "{{ ec2_output.results }}"
    when:
      - item.item == "frontend"
      - action == "create"


  - name: delete r53 records
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ item }}-{{ Env }}.{{ domain_name }}" # roboshop-dev.daws88s.online
      type: A
      ttl: 1
    loop: "{{ instances }}"
    when: action == "destroy"

  - name: delete ec2 instance
    amazon.aws.ec2_instance:
      state: absent
      name: "{{ item }}-{{ Env }}"
      wait: false
    loop: "{{ instances }}"
    when: action == "destroy"

