- name: Create ec2 instances and route 53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-0bd66f913b1217939
    ami_id: ami-0220d79f3f480ecf5
    Env: dev
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ Env }}"
      tags:
        project: RoboShop
        component: "{{ item }}"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ Env }}"
    loop: "{{ instances }}"
    register: "{{ ec2_output }}"
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
      "

