- name: configuring user module
  hosts: user
  become: yes
  tasks:
  - name: enabling nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs:20 
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: adding user
    ansible.builtin.user:
      home: /app
      system: true
      shell: /sbin/nologin
      name: roboshop
      comment: roboshop system user

  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete user zip file & directory
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent

  - name: downloading user code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: unzipping user code
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: installing nodejs dependencies
    community.general.npm:
      path: /app

  - name: copy user service file
    ansible.builtin.template:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reexec: true

  - name: enable and start user
    ansible.builtin.service:
      name: user
      enabled: yes
      state: restarted
    
      
